name: Build
on:
  workflow_run:
    workflows: ["Format"]
    types:
      - completed
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event.workflow_run.conclusion == 'success' &&
       contains(github.event.workflow_run.head_commit.message, '(release)'))

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Install UV
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync

      - name: Update project keywords
        env:
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: uv run ./scripts/keywords.py $REPO_OWNER $REPO_NAME

      - name: Build project
        run: uv build

      # TODO: publish to PyPI

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
              echo "changed=true" >> $GITHUB_OUTPUT
          else
              echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "refactor: auto-update project keywords"
          git push
