name: Format
on:
    push:
        branches:
            - "**"

jobs:
    format:
        name: Format code
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install uv
              uses: astral-sh/setup-uv@v6

            - name: Run ruff
              run: uvx ruff format

            - name: Check for changes
              id: verify-changed-files
              run: |
                  if [ -n "$(git status --porcelain)" ]; then
                      echo "changed=true" >> $GITHUB_OUTPUT
                  else
                      echo "changed=false" >> $GITHUB_OUTPUT
                  fi

            - name: Commit and push changes
              if: steps.verify-changed-files.outputs.changed == 'true'
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add .
                  git commit -m "Auto-format code with ruff"
                  git push
